Updated from RStudio workbench to server
saturncloud/recipes pull request #5
Opened 2021-11-11 22:30 UTC by jnolis

This changes the following:

1. RStudio workbench has been renamed to RStudio server, both since we're not using workbench (the paid RStudio server version), and since RStudio server is the terminology we're using within Saturn Cloud
2. Added "bioconductor" as an additional option for where to install R packages from, to match https://app.clickup.com/t/1250339/DEV-2899

2021-11-12 14:08 UTC, forana approved these changes
Changes LGTM - had one question.

2021-11-12 14:08 UTC, forana commented on resources/schema.json
> +          "description": "List of packages to install from CRAN, each separated by a space(RStudio Server only)"
Should we really be removing the `[FUTURE RELEASE]` here? No idea when we'll have support for any of these extra package types.

2021-11-15 15:43 UTC, jsignell reviewed
Before we merge this let' figure out how to handle releases on this repo

2021-11-15 15:56 UTC, jsignell requested changes

2021-11-15 15:56 UTC, jsignell commented on resources/schema.json
> +          "description": "Packages to install from Bioconductor, each separated by a space (RStudio Server only)"
We should have `[FUTURE RELEASE]` on all of these

2021-11-17 19:36 UTC, jsignell commented
@forana is this for 2021.11.10?

2021-11-17 20:37 UTC, forana commented
> @forana is this for 2021.11.10?

I suppose to - `rstudio_server` shouldn't be used on releases earlier than `11.10`.

2021-11-19 19:52 UTC, jnolis commented
Okay I put back the "future release" note on the R package stuff. Is this good to go @jsignell & @forana ?

2021-11-22 15:44 UTC, jsignell approved these changes

2021-11-22 15:45 UTC, merged